### ISSUE TITLE
[Bug]: label field not working

### ISSUE THREAD

**Issue by divshacker** [geromegrignon/issue-forms-creator#4]
### Description

When we make any new form. The label field in the issue header is not working as expected. 

### Minimal Reproduction

Just make a new form and try adding label to the form. It will not add. Not in preview and not in copied `yaml` code. 

### Exception or Error

No errors.

**Comment by divshacker** [comment]
The behaviour is same for `add assignee` too.

**Comment by geromegrignon** [comment]
Thanks for the explanation.

I'll add guidance about how this field works: you have to hit enter after typing the name of the label to add it.
